server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org:
      springframework: INFO
