spring:
  session:
    cookie:
      name: JSESSIONID
      path: /
      http-only: true
      same-site: none
      secure: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  mvc:
    view:
      prefix: ''
      suffix: ''
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: softuni
    username: root
    url: jdbc:mysql://localhost:3307/pet_manager_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  thymeleaf:
    enabled: false
    cache: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
      tracking-modes:
        - COOKIE
  port: 8081
